bayes_people_tracker:
    detectors:                                                 # Add detectors under this namespace
        left_tracker:                                          # Name of detector (used internally to identify them. Has to be unique.
            topic: "/to_pose_array/circle_detector_left"       # The topic on which the geometry_msgs/PoseArray is published
            noise_model:
                velocity:                                      # The std deviation for the constant velocity model
                    x: 0.4
                    y: 0.4
                position:                                      # The std deviation for the cartesian model
                    x: 0.2
                    y: 0.2
            matching_algorithm: "NNJPDA"                       # The algorthim to match different detections. NN = Nearest Neighbour, NNJPDA = NN + Joint Probability Data Association
        right_tracker:                                          # Name of detector (used internally to identify them. Has to be unique.
            topic: "/to_pose_array/circle_detector_right"               # The topic on which the geometry_msgs/PoseArray is published
            noise_model:
                velocity:                                      # The std deviation for the constant velocity model
                    x: 0.4
                    y: 0.4
                position:                                      # The std deviation for the cartesian model
                    x: 0.2
                    y: 0.2
            matching_algorithm: "NNJPDA"                       # The algorthim to match different detections. NN = Nearest Neighbour, NNJPDA = NN + Joint Probability Data Association
